routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('welcome');
// });

// Route::get('socket', 'Admin\DashboardController@socket');
// Route::get('socket1', 'Admin\DashboardController@socket1');

Route::get('/rfpanel/become_driver', function() {
	return redirect()->route('website.become_driver');
});

Route::get('socket_driver', 'GeneralController@socket');
Route::get('socket_rider', 'GeneralController@socket_patient');


Route::group(['namespace'=>'website','as'=>'website.'],function(){
	Route::get('/','HomeController@index')->name('home');
	Route::get('become_driver','HomeController@becomeDriver')->name('become_driver');
	Route::get('cities','HomeController@cities')->name('cities');
	Route::get('driver_requirements','HomeController@driverRequirements')->name('driver_requirements');
	Route::get('privacy_policy','HomeController@privacyPolicy')->name('privacy_policy');
	Route::get('getting_started','HomeController@gettingStarted')->name('getting_started');
	Route::post('addBecomeDriver','HomeController@addBecomeDriver')->name('addBecomeDriver');
	Route::get('contact_us','HomeController@contactUs')->name('contact_us');
	Route::get('faq','HomeController@faq')->name('faq');
	Route::get('how_to_ride','HomeController@howToRide')->name('how_to_ride');
	Route::get('fares','HomeController@fares')->name('fares');
});

Route::group(['prefix'=> 'rfupanel', 'namespace'=>'Admin\Auth','as'=>'admin.'],function(){

	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['prefix'=> 'rfupanel', 'namespace'=>'Admin','as'=>'admin.','middleware'=>'auth:admin'],function(){
	Route::get('/', 'DashboardController@dashboard')->name('dashboard');
	// other dashboards
	Route::get('/payment', 'DashboardController@payment')->name('payment');

	Route::get('/secondDashboard', 'DashboardController@secondDashboard');
	Route::get('/thirdDashboard', 'DashboardController@thirdDashboard');
	Route::get('/fourthDashboard', 'DashboardController@fourthDashboard');

	/** driver / Rider  **/
	Route::get('getUsersList', 'UserController@getUsersList')->name('users.getUsersList');
	Route::get('userProfileApprove/{id}','AdminUserAccessController@user_profile_approve_admin')->name('users.approve');
	Route::Resource('users','UserController');
	Route::get('editRiderProfile','UserController@edit_rider_profile')->name('rider.edit.profile.data');
	Route::post('riders/update/{id}', 'UserController@update')->name('users.update');

	Route::Resource('drivers','DriverController');

	/* route for listing trip for user and driver */
	Route::get('trips/{id}','TripController@list_user_trips')->name('displayUserTrips');
	Route::get('triplist/{id}','TripController@list_driver_trips')->name('displayDriverTrips');

	/* Admin approve driver profile */
	Route::get('/driverProfileApprove','AdminUserAccessController@driver_profile_approve_admin')->name('driver.approve');
	/* user details page */
	Route::get('/driverDetails/{id}','DriverController@driver_details_function')->name('driver.show');

	/*route for payment listing */
	Route::get('payments/{id}','PaymentController@list_user_payments')->name('displayUserpayments');
	Route::get('paymentlist/{id}','PaymentController@list_Driver_payments')->name('displayDriverpayments');

	/*code for add driver profile */
	Route::get('adddriver_profile/{id}','DriverController@adddriver_profile')->name('adddriver_profile');
	Route::get('addDriverProfile/{id}','DriverController@show_driver_profile')->name('addDriverProfile');
	Route::post('addDriveraddress/{id}','DriverController@add_driver_address')->name('updateDriverProfile');

	// Route::post('drivers/update/{id}', 'DriverController@update')->name('drivers.update');

	/* Manage driver documents */
	Route::Resource('driverManageDocuments','DriverManageController');
	Route::get('drivermanageDocument/{id}','DriverManageController@view')->name('driverManageDocuments.view');

	/*code for documents */
	Route::get('listDocuments/{id}','DriverCarDetailsController@list_documents')->name('listDocuments');
	Route::post('submitDocuments','DriverCarDetailsController@submit_Documents')->name('submitDocuments');
	Route::get('deleteDocuments/{id}','DriverCarDetailsController@delete_document')->name('deleteDocuments');

	/* trip history */
	Route::get('tripHistory','TripController@trip_history_upcoming')->name('upcoming.trips');
	Route::get('completeHistory','TripController@trip_history_complete')->name('complete.trips');
	Route::get('triplist','TripController@get_trip_list')->name('trip.history');
	Route::get('tripdetails/{id}','TripController@get_trip_details')->name('trip.details');
	Route::get('giveBookingRefund/{booking_id}','TripController@giveBookingRefund')->name('trip.giveBookingRefund');
	Route::post('bookingRefund/{booking_id}','TripController@bookingRefund')->name('trip.bookingRefund');

	Route::get('chargeDriver/{trip_id}','TripController@chargeDriver')->name('trip.chargeDriver');
	Route::post('tripCharge/{trip_id}','TripController@tripCharge')->name('trip.tripCharge');

	/* code for list vehicles */
	Route::get('listVehicles/{id}','DriverCarDetailsController@list_vehicles')->name('ViewVehicalesList');
	Route::get('addVehicles/{id}','DriverCarDetailsController@add_vehicles_page')->name('addVehicles');
	Route::post('addVehiclesform','DriverCarDetailsController@add_vehicles')->name('addVehiclesForm');
	Route::post('addVehicles','DriverCarDetailsController@delete_vehicles')->name('deleteVehiclesForm');

	/* Payment history */
	Route::get('paymentHistory','PaymentController@get_payment_history')->name('payment_history');
	Route::get('paymentlist','PaymentController@get_payment_list')->name('payment.history');
	Route::get('/totalEarning', 'PaymentController@totalEarning')->name('totalEarning');

	/* Route for add car details*/
	Route::post('addDriverCarDetails','DriverController@add_car_details')->name('add.carDetails');
	/* driver car details */
	Route::Resource('driverCarDetails','DriverCarDetailsController');
	Route::post('DriverCarDetailsList','DriverCarDetailsController@car_details_list')->name('driverCarDetails.list');
	Route::post('DriverCarDetailsEdit','DriverCarDetailsController@get_edit_car_data')->name('get.edit.data');

	Route::get('getProducts', 'GlobalSettingController@show_products_page')->name('products.product');
	Route::apiResource('products','GlobalSettingController');
	Route::post('appSettingStore', 'GlobalSettingController@appSettingStore')->name('products.appSetting');
	Route::post('adminFees', 'GlobalSettingController@adminFees')->name('products.adminFees');

	Route::post('get_work_countries', 'WorkCountryController@show_work_countries')->name('work_countries.work_countries');
	Route::Resource('work_countries','WorkCountryController');

	Route::post('get_work_cities', 'WorkCityController@show_work_cities')->name('work_cities.work_cities');
	Route::Resource('work_cities','WorkCityController');
	Route::get('get_state/{id}', 'WorkCityController@get_state')->name('work_city.get_state');



	/* STATE */
	Route::post('create_state', 'WorkStateController@create_state')->name('create_state');
	Route::get('getStateList', 'WorkStateController@getStateList')->name('getStateList');
	Route::put('update_state/{id}', 'WorkStateController@update_state')->name('update_state');

	Route::post('get_work_locations', 'WorkLocationController@show_work_locations')->name('work_locations.work_locations');
	Route::get('get_cities_by_country/{id}', 'WorkLocationController@get_cities_by_country')->name('work_locations.get_cities_by_country');
	Route::Resource('work_locations','WorkLocationController');

	//Route::post('getJobList', 'JobHistoryController@getJobList')->name('jobhistory.getJobList');
	//Route::apiResource('jobhistory','JobHistoryController');

	/* Admin approve user profile and send mail */
	Route::get('approveMail','UserController@user_approval_comment_mail')->name('approval.mail');
	/* Admin approve user profile and send mail */
	Route::get('approvedMail','DriverController@driver_approval_comment_mail')->name('approvals.mail');


	/* Car Route */
	Route::Resource('carCompany','CarCompanyController');
	Route::post('carCompanyList','CarCompanyController@list')->name('carcompany.list');
	Route::post('carCompanyname','CarCompanyController@get_edit_company_name')->name('carcompany.edit.name');

	/* OFFICE  INFOMATION*/
	Route::Resource('officeInformations','OfficeInformationController');
	Route::get('createOffice','OfficeInformationController@createOffice')->name('office.create');
	Route::post('addOffice','OfficeInformationController@addOffice')->name('office.add');
	Route::get('listOffice','OfficeInformationController@listOffice')->name('office.list');
	Route::delete('deleteOffice','OfficeInformationController@deleteOffice')->name('office.delete');
	Route::get('editOffice/{id}','OfficeInformationController@editOffice')->name('office.edit');
	Route::post('updateOffice','OfficeInformationController@updateOffice')->name('office.update');

	/* Car types*/
	Route::Resource('carType','CarTypesController');

app/Http/Controllers/Api/v3/DriverController.php
<?php

namespace App\Http\Controllers\Api\v3;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use Auth;
use App\Used_document;
use App\OfficeInformation;

class DriverController extends Controller
{
    /** driver language update **/
	public function updateDriverLanguages(Request $request) 
	{
		
		$user   = 	Auth::user();

		$validator = Validator::make($request->all(),[
			'languages_known' => "required | json",
		]);

		if ($validator->fails()) {
			return response()->json(['status'=>false,'message' => $validator->messages()->first()]);
		}

		$user->languages_known = json_decode($request->get('languages_known'));
		$user->save();

		return response()->json(['status'=>true,'message' => 'Information updated successfully.','data'=>$user->languages_known]); 
	}

	/**Vehivle info**/
	public function vehicleInfo() 
	{ 
		$user 		= Auth::user();
		$userdata	= $user->driver()->select('id')
										->with(['car_driver'=> function ($query) {
											$query->select('id','driver_id','car_model_id','color','year','rules_and_regulations','allowed_things');
										}])
										->where('user_id',$user->id)
										->first();
		
		$userdata->car_driver = collect($userdata->car_driver)->map(function ($cars)  {

			$cars->company 					= $cars->car_model->car_company['name'];
			$cars->type 					= $cars->car_model->car_type['name'];
			$cars->model 					= $cars->car_model['model_name'];
			$cars->capacity 				= $cars->car_model['capacity'];
			$cars->color 					= $cars->color;
			$cars->year 					= $cars->year;
			$cars->carPhoto 				= $cars->carPhotoes;
			$cars->rules_and_regulations 	= $cars->rules_and_regulations;
			$cars->allowed_things 			= $cars->allowed_things;
			$cars->logo 					= $cars->car_model->car_type['logo'];
			unset($cars->car_model);
			unset($cars->carPhotoes);

		});
		$userdata->base_url 				= asset('storage/driver_car').'/'.$userdata->id.'/';

		return response()->json(['status'=>true,'message'=>'Vehicle info retrieved Successfully.','data' => $userdata]); 
	} 

	/** update driver additional info **/
	public function updateDriverAdditionalInfo(Request $request) 
	{ 
		$input 	= $request->all();
		$user   = Auth::user();

		$validator = Validator::make($input,[
			'additional_info' => "required|string",
		]);

		if ($validator->fails()) {
			return response()->json(['status'=>false,'message' => $validator->messages()->first()]);
		}

		$user->additional_info = $request->get('additional_info');
		$user->save();

		return response()->json(['status'=>true,'message' => 'Information updated successfully.']); 
	} 

	/** driver document status api **/
	public function driverDocuments() 
	{ 
		$user = Auth::user();

		$userDocs = Used_document::where('ownable_id',$user->driver->id)->pluck('expiry_date','document_id')->toArray();

		$documents = collect([
			'1' => ['name' => 'driver_licence'],
			'2'	=> ['name' => 'proof_of_work_eligibility'],
			'3' => ['name' => 'criminal_certificate'],
			'4' => ['name' => 'profile_photo'],
		]);
		$uploadedDocs = array_keys($userDocs);
		$docs = [];
		foreach ($documents as $key => $doc) {
			if(in_array($key, $uploadedDocs)){
				$docs[$doc['name']] = array('status'=>"provided",'data'=>$userDocs[$key]);
				if($userDocs[$key] < date('Y-m-d')){
					$docs[$doc['name']] = array('status'=>"expired",'data'=>$userDocs[$key]);
				}
			}else{
				$docs[$doc['name']] = array('status'=>"not_provided",'data'=>'');
			}
			if($key == '4' && $user->profile_pic != null && file_exists(storage_path().'/app/public/images/users/'.$user->id.'/profile_pic/'.$user->profile_pic)){
				$docs[$doc['name']] = array('status'=>"provided",'data'=>asset('storage/images/users/'.$user->id.'/profile_pic/'.$user->profile_pic));
			}
		}
		$response = [];
		$response['driver_docs'] = $docs;
		$car_drivers=$user->driver->car_driver;

		if(count($car_drivers) > 0){
			$docs = [];
			$i=0;
			foreach ($car_drivers as $key => $car_driver) {

				$carDocs = Used_document::where('ownable_id',$car_driver->id)->pluck('expiry_date','document_id')->toArray();

				$documents = collect([
					'4'  => ['name' => 'vehicle_registration'],
					'5'  => ['name' => 'vehicle_insurance']
				]);

				$uploadedDocs = array_keys($carDocs);
				
				foreach ($documents as $key => $doc) {
					$docs[$i]['car_detail']=array(
						'car_no'=>$car_driver->car_number,
						'model'=>$car_driver->car_model['model_name'],
						'company'=>$car_driver->car_model->car_company['name'],
						'car_type'=>$car_driver->car_model->car_type['name'],
					);
					if(in_array($key, $uploadedDocs)){
						$docs[$i][$doc['name']] = array('status'=>"provided",'expiry_date'=>$carDocs[$key]);
						if($carDocs[$key] < date('Y-m-d')){
							$docs[$i][$doc['name']] = array('status'=>"expired",'expiry_date'=>$carDocs[$key]);
						}
					}else{
						$docs[$i][$doc['name']] = array('status'=>"not_provided",'expiry_date'=>'');
					}
				}
				$i++;
			}
		}

		$response['car_docs'] = $docs;

		// return $response;
		return response()->json(['status'=>true,'message'=>'Information retrived successfully.','data' => $response]); 
	} 

	/** office Info **/
	public function officeInfo(Request $request){

		$validator = Validator::make($request->all(),[
			'city' => "required"
		]);

		if ($validator->fails()) { 
			return response()->json(['status'=>false,'message'=>$validator->messages()->first()]);            
		}
		$user = Auth::user();
		$officeInfo = OfficeInformation::where('city',$request->get('city'))
		->first();
		if ($officeInfo) {
			$location_hours=explode(',', $officeInfo['location_hours']);
			$inquiry_hours=explode(',', $officeInfo['inquiry_hours']);
			
			$officeInfo['location_hours'] = $location_hours[0].'-'.$location_hours[1].' : '.$location_hours[2].' - '.$location_hours[3];
			$officeInfo['inquiry_hours']  = $inquiry_hours[0].'-'.$inquiry_hours[1].' : '.$inquiry_hours[2].' - '.$inquiry_hours[3];
			if ($officeInfo) {
				return response()->json(['status'=>true,'message'=>'Office Information','data'=>$officeInfo]);
			} else {
				return response()->json(['status'=>false,'message'=>'Sorry! RideChimp currently not available in your city.','data'=>['id'=>0,
					'city'=>'',
					'country'=>'',
					'postal_code'=>'',
					'longitude'=>'',
					'latitude'=>'',
					'full_address'=>'',
					'location_hours'=>'',
					'inquiry_hours'=>'',
					'phone'=>'',
					'email'=>'',
					'created_at'=>'',
					'updated_at'=>'',
				]]);
			}
		} else {
			return response()->json(['status'=>false,'message'=>'Sorry! RideChimp currently not available in your city.','data'=>['id'=>0,
				'city'=>'',
				'country'=>'',
				'postal_code'=>'',
				'longitude'=>'',
				'latitude'=>'',
				'full_address'=>'',
				'location_hours'=>'',
				'inquiry_hours'=>'',
				'phone'=>'',
				'email'=>'',
				'created_at'=>'',
				'updated_at'=>'',
			]]);
		}
	}

	/** update driver address **/
	public function updateDriverAddress(Request $request) 
	{ 
		$input 	= $request->all();
		$user   = Auth::user();

		$validator = Validator::make($input,[
			'address' => "required",
		]);

		if ($validator->fails()) {
			return response()->json(['status'=>false,'message' => $validator->messages()->first()]);
		}
		$user->address = $request->get('address');
		$user->living_address = $request->get('address');
		$user->save(); 

		return response()->json(['status'=>true,'message' => 'Information updated successfully.']); 
	} 

}

resources/views/admin/drivers/add_driver_profile.blade.php
@extends('admin.layouts.admin-app')
<?php //die(); ?>
@section('content') 
<div class="page-wrapper">
    <!-- Main Content -->
    <div class="container-fluid pt-25">
        <div class="back_button">
            <a href="{{route('admin.users.index')}}"><button class="btn btn btn-success">Back</button></a>
        </div>
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h5 class="txt-dark">Driver Profile</h5>
            </div>
          <!-- Breadcrumb -->
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                    <li><a href="{{route('admin.users.index')}}">Users List</a></li>
                    <li class="active"><span>Driver Profile</span></li>
                </ol>
            </div>
            <!-- /Breadcrumb -->
        </div>
    <!--  -->
   
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default card-view BoxDesignCoverInerCla1">
                    <div class="panel-heading">
                        <div class="pull-left">
                            
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="form-wrap">
                                <form  method="POST" id="Add_driver_address" data-toggle="validator">
                                    <div class="colmd12fullwidth">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left" for="example-email"><span class="help">Street Address</span></label>
                                                <input type="text" id="street_address" name="street_address" class="form-control" placeholder="Street Address" required=""  value="{{$datas['street_address']}}">
                                                <input type="hidden" name="id" id="id" value="@if(isset($User_id)){{$User_id}}@endif">
                                                <div class="help-block with-errors"></div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="control-label mb-10 text-left" for="example-email"><span class="help">City</span></label>
                                                <input type="text" id="city" name="city" class="form-control" placeholder="City" required="" value="@if(isset($id)){{$datas['city']}}@endif">
                                                <div class="help-block with-errors"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="colmd12fullwidth">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left" for="example-email"><span class="help">state</span></label>
                                                <input type="text" name="state" class="form-control" placeholder="State" required=""  value="@if(isset($id)){{$datas['state']}}@endif">
                                                <div class="help-block with-errors"></div>
                                            </div>
                                        </div>
                                         <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left" for="example-email"><span class="help">Country</span></label>
                                                <input type="text" id="country" name="country" class="form-control" placeholder="Country" required="" value="@if(isset($id)){{$datas['country']}}@endif">
                                                <div class="help-block with-errors"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="colmd12fullwidth">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left" for="example-email"><span class="help">Postal Code</span></label>
                                                <input type="text" id="pincode" minlength="6" maxlength="6" name="pincode" class="form-control" placeholder="Postal Code" required=""  value="@if(isset($id)){{$datas['pincode']}}@endif">
                                                <div class="help-block with-errors"></div>
                                            </div>
                                        </div>
                                        {{--<div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left" for="example-email"><span class="help">Profile Approval</span></label>
                                                <input type="checkbox" class="js-switch js-switch-1 user_Profile_approval" data-switchery="false" data-color="#dc4666" data-secondary-color="#ea6c41"  data-id="{{$id}}" @if(!empty($datas['is_approved']) && $datas['is_approved'] == '1') checked="checked" @endif/>
                                            </div>
                                        </div>  --}}    
                                    </div>
                                    <div class="colmd12fullwidth2">
                                        <button type="submit" id="Update" data-loading-text="<i class='fa fa-spinner'></i>" class="btnsetm">Save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Row -->
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">

    

    /*code for add driver address*/

    $('#Add_driver_address').submit(function(e){
        e.preventDefault();
        form=$('#Add_driver_address');
        var formData = new FormData(form[0]);       
        var id = $('#id').val();

        if ($('#Add_driver_address').validator('validate').has('.has-error').length === 0) {

            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method:'POST',
                url:"{{route('admin.updateDriverProfile','')}}/"+id,
                data:formData,
                cache:false,
                processData: false,
                contentType: false,
                 beforeSend: function(){
                   $('#update').button('loading');
                },
                success:function(data) {
                    switch (data.status) {
                        case true:
                        toastr.success(data.message);
                        location.reload();
                        break;
                        case false:
                        toastr.error(data.message);
                        break;
                    }
                },
                complete: function(){
                  $('#update').button('reset');
                }
            });
        }
    });
</script>
@endsection

resources/views/admin/drivers/vehiclesList.blade.php
@extends('admin.layouts.admin-app')

@section('content')
<div class="page-wrapper">
    <!-- Main Content -->
    <div class="container-fluid pt-25">
        <div class="back_button">
            <a href="{{route('admin.users.index')}}"><button class="btn btn btn-success">Back</button></a>
        </div>
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h5 class="txt-dark">Vehicles list</h5>
            </div>
          <!-- Breadcrumb -->
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                    <li><a href="{{route('admin.users.index')}}">Users List</a></li>
                    <li class="active"><span>Vehicles list</span></li>
                </ol>
            </div>
            <!-- /Breadcrumb -->
        </div>
    <!--  -->
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default card-view BoxDesignCoverInerCla1">
                    <div class="panel-heading">
                        <div class="MyVehicles_maintitlebox">
                           <!-- <p>My Vehicles</p> -->
                        </div>
                        <div class="AddVehicles_Btnbox">
                                <a href="{{route('admin.addVehicles',$data[0]->id)}}" id="Update" data-loading-text="<i class='fa fa-spinner'></i>" class="">Add Vehicle</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="vehicle_list">
                                <div class="car">
                                    @foreach($datass as $key => $datas)
                                    <div class="car_list">
                                        <div class="VehiclesListBoxdesign">
                                            {{$datas->year}} {{$datas->car_model->model_name}} - {{$datas->color}} - {{$datas->car_model->capacity}} Seats<a href="javascript:void(0);" class="delete_vehicles" data-id="{{$datas->id}}"><i class="fa fa-trash" aria-hidden="true"></i></a>

                                        </div>
                                    </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
        <!-- /Row -->
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
        
    $(document).on('click','.delete_vehicles',function(e){
        var id = $(this).data('id');

        e.preventDefault();

        swal({
            title: "Are you sure?",   
            text: "You will not be able to recover this information!",   
            type: "warning",   
            showCancelButton: true,   
            confirmButtonColor: "#e69a2a",   
            confirmButtonText: "Yes, delete it!",   
            cancelButtonText: "No, cancel please!",   
            closeOnConfirm: false,   
            closeOnCancel: false 
        },
        function(isConfirm){   
            if (isConfirm) {
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN':  "{{ csrf_token() }}"
                    },
                    method:'POST',
                    url:"{{route('admin.deleteVehiclesForm')}}",
                    data:{'id':id,"_token":'{{csrf_token()}}'},
                    beforeSend: function(){
                       $('#update').button('loading');
                    },
                    success:function(data) {
                        $('#docid_delete').val('');
                        switch (data.status) {
                        case true:
                        swal("Deleted!", "Your Document has been deleted.", "success");  
                        location.reload();
                        toastr.success(data.message);
                        break;
                        case false:
                        toastr.error(data.message);
                        break;
                    }
                    },
                });
            } else {
                swal("Cancelled", "Your Document is safe! :)", "error"); 
            }
        })
    });

</script>
@endsection