routes/web.php
	/* user details page */
	Route::get('/driverDetails/{id}','DriverController@driver_details_function')->name('driver.show');

	/*route for payment listing */
	Route::get('payments/{id}','PaymentController@list_user_payments')->name('displayUserpayments');
	Route::get('paymentlist/{id}','PaymentController@list_Driver_payments')->name('displayDriverpayments');

	/*code for add driver profile */
	Route::get('adddriver_profile/{id}','DriverController@adddriver_profile')->name('adddriver_profile');
	Route::get('addDriverProfile/{id}','DriverController@show_driver_profile')->name('addDriverProfile');
	Route::post('addDriveraddress/{id}','DriverController@add_driver_address')->name('updateDriverProfile');

	// Route::post('drivers/update/{id}', 'DriverController@update')->name('drivers.update');

	/* Manage driver documents */
	Route::Resource('driverManageDocuments','DriverManageController');
	Route::get('drivermanageDocument/{id}','DriverManageController@view')->name('driverManageDocuments.view');

	/*code for documents */
	Route::get('listDocuments/{id}','DriverCarDetailsController@list_documents')->name('listDocuments');
	Route::post('submitDocuments','DriverCarDetailsController@submit_Documents')->name('submitDocuments');
	Route::get('deleteDocuments/{id}','DriverCarDetailsController@delete_document')->name('deleteDocuments');

	/* trip history */
	Route::get('tripHistory','TripController@trip_history_upcoming')->name('upcoming.trips');
	Route::get('completeHistory','TripController@trip_history_complete')->name('complete.trips');
	Route::get('triplist','TripController@get_trip_list')->name('trip.history');
	Route::get('tripdetails/{id}','TripController@get_trip_details')->name('trip.details');
	Route::get('giveBookingRefund/{booking_id}','TripController@giveBookingRefund')->name('trip.giveBookingRefund');
	Route::post('bookingRefund/{booking_id}','TripController@bookingRefund')->name('trip.bookingRefund');

	Route::get('chargeDriver/{trip_id}','TripController@chargeDriver')->name('trip.chargeDriver');
	Route::post('tripCharge/{trip_id}','TripController@tripCharge')->name('trip.tripCharge');

	/* code for list vehicles */
	Route::get('listVehicles/{id}','DriverCarDetailsController@list_vehicles')->name('ViewVehicalesList');
	Route::get('addVehicles/{id}','DriverCarDetailsController@add_vehicles_page')->name('addVehicles');
	Route::post('addVehiclesform','DriverCarDetailsController@add_vehicles')->name('addVehiclesForm');
	Route::post('addVehicles','DriverCarDetailsController@delete_vehicles')->name('deleteVehiclesForm');

	/* Payment history */
	Route::get('paymentHistory','PaymentController@get_payment_history')->name('payment_history');
	Route::get('paymentlist','PaymentController@get_payment_list')->name('payment.history');
	Route::get('/totalEarning', 'PaymentController@totalEarning')->name('totalEarning');

	/* Route for add car details*/
	Route::post('addDriverCarDetails','DriverController@add_car_details')->name('add.carDetails');
	/* driver car details */
	Route::Resource('driverCarDetails','DriverCarDetailsController');
	Route::post('DriverCarDetailsList','DriverCarDetailsController@car_details_list')->name('driverCarDetails.list');
	Route::post('DriverCarDetailsEdit','DriverCarDetailsController@get_edit_car_data')->name('get.edit.data');

	Route::get('getProducts', 'GlobalSettingController@show_products_page')->name('products.product');
	Route::apiResource('products','GlobalSettingController');
	Route::post('appSettingStore', 'GlobalSettingController@appSettingStore')->name('products.appSetting');
	Route::post('adminFees', 'GlobalSettingController@adminFees')->name('products.adminFees');

	Route::post('get_work_countries', 'WorkCountryController@show_work_countries')->name('work_countries.work_countries');
	Route::Resource('work_countries','WorkCountryController');

	Route::post('get_work_cities', 'WorkCityController@show_work_cities')->name('work_cities.work_cities');
	Route::Resource('work_cities','WorkCityController');
	Route::get('get_state/{id}', 'WorkCityController@get_state')->name('work_city.get_state');



	/* STATE */
	Route::post('create_state', 'WorkStateController@create_state')->name('create_state');
	Route::get('getStateList', 'WorkStateController@getStateList')->name('getStateList');
	Route::put('update_state/{id}', 'WorkStateController@update_state')->name('update_state');

	Route::post('get_work_locations', 'WorkLocationController@show_work_locations')->name('work_locations.work_locations');
	Route::get('get_cities_by_country/{id}', 'WorkLocationController@get_cities_by_country')->name('work_locations.get_cities_by_country');
	Route::Resource('work_locations','WorkLocationController');

	//Route::post('getJobList', 'JobHistoryController@getJobList')->name('jobhistory.getJobList');
	//Route::apiResource('jobhistory','JobHistoryController');

	/* Admin approve user profile and send mail */
	Route::get('approveMail','UserController@user_approval_comment_mail')->name('approval.mail');
	/* Admin approve user profile and send mail */
	Route::get('approvedMail','DriverController@driver_approval_comment_mail')->name('approvals.mail');


	/* Car Route */
	Route::Resource('carCompany','CarCompanyController');
	Route::post('carCompanyList','CarCompanyController@list')->name('carcompany.list');
	Route::post('carCompanyname','CarCompanyController@get_edit_company_name')->name('carcompany.edit.name');

	/* OFFICE  INFOMATION*/
	Route::Resource('officeInformations','OfficeInformationController');
	Route::get('createOffice','OfficeInformationController@createOffice')->name('office.create');
	Route::post('addOffice','OfficeInformationController@addOffice')->name('office.add');
	Route::get('listOffice','OfficeInformationController@listOffice')->name('office.list');
	Route::delete('deleteOffice','OfficeInformationController@deleteOffice')->name('office.delete');
	Route::get('editOffice/{id}','OfficeInformationController@editOffice')->name('office.edit');
	Route::post('updateOffice','OfficeInformationController@updateOffice')->name('office.update');

	/* Car types*/
	Route::Resource('carType','CarTypesController');
	Route::post('carTypeList','CarTypesController@list')->name('cartype.list');
	Route::post('carTypename','CarTypesController@get_edit_type_name')->name('cartype.edit.name');
	Route::post('carTypeUpdate/{id}','CarTypesController@update_car_type')->name('carType.update_type');
	/* Car Models */
	Route::Resource('carModel','CarModelController');
	Route::post('carModelList','CarModelController@list')->name('carmodel.list');
	Route::post('carModelname','CarModelController@get_edit_model_name')->name('carmodel.edit.name');

	/* Driver detail page this one for get car detail of a driver */
	Route::post('driverCarDetails','DriverController@get_car_details_of_drivers')->name('driver.cardetails');
	Route::post('driverCarPhoto','DriverController@car_photo')->name('car.photo');
	Route::get('editBankDetails/{id}','DriverController@editBankDetails')->name('editBankDetails');
	Route::post('updateBankDetails','DriverController@updateBankDetails')->name('drivers.updateBankDetails');

	Route::get('editDriverProfile','DriverController@edit_driver_profile')->name('driver.edit.profile.data');
	Route::Resource('manageDocuments','DocumentController');
	Route::get('manageDocument/{id}','DocumentController@view')->name('manageDocuments.view');
	/* ajax category subcategory routes for get car company,type ane model in driver details page */
	Route::get('driverCartype/{id}','DriverController@get_type_by_company')->name('cartype.carcompany');
	Route::post('driverCarmodel','DriverController@get_model_by_type')->name('carmodel.cartype');

	/* ORDER */
	Route::get('orderList','OrderController@index')->name('orderList');
	Route::get('orderDetails/{id}','OrderController@orderDetails')->name('orderDetails');
	Route::get('getOrderList','OrderController@getOrderList')->name('getOrderList');
	Route::get('maps','OrderController@maps')->name('maps');

	//Route::get('cancelledBookings','OrderController@cancelledBookings')->name('cancelledBookings');
	Route::get('/cancelledBookings', 'TripController@cancelledBookings')->name('cancelledBookings');
	Route::get('/getRiderStatus', 'TripController@getRiderStatus')->name('rider_status');
	Route::get('/getDriverStatus', 'TripController@getDriverStatus')->name('driver_status');
	Route::get('/getReportStatus', 'TripController@getReportStatus')->name('report_status');

	/** allowed / notallowed things **/
	Route::post('get_allowed_things', 'AllowedThingsController@show_allowed_things')->name('allowed_things.get_allowed_things');
	Route::post('get_notallowed_things', 'AllowedThingsController@show_notallowed_things')->name('allowed_things.get_notallowed_things');

	Route::resource('allowed_things','AllowedThingsController');

	/** Booking/Trip Cancellation reasons **/
	Route::post('get_rider_trip_cancellation_reasons', 'TripCancellationReasonController@rider_trip_cancellation_reasons')->name('cancellation_reasons.rider_trip_cancellation_reasons');
	Route::post('get_driver_trip_cancellation_reasons', 'TripCancellationReasonController@driver_trip_cancellation_reasons')->name('cancellation_reasons.driver_trip_cancellation_reasons');
	Route::post('get_driver_booking_decline_reasons', 'TripCancellationReasonController@driver_booking_decline_reasons')->name('cancellation_reasons.driver_booking_decline_reasons');

	Route::resource('cancellation_reasons','TripCancellationReasonController');

	/* fare management */
	Route::get('/fareManagement', 'FareManagementController@index')->name('fareManagement');
	Route::post('/addFare', 'FareManagementController@addFare')->name('addFare');
	Route::get('/fareList', 'FareManagementController@fareList')->name('fareList');
	Route::post('/editFare', 'FareManagementController@editFare')->name('editFare');
	Route::delete('/deleteFare/{id}', 'FareManagementController@deleteFare')->name('deleteFare');
});
Auth::routes();

app/Work_city.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Work_city extends Model
{
	protected $fillable = [
		'name','work_country_id','work_state_id','timezone_name','timezone'
	];

	public function work_country(){
		return $this->belongsTo('App\Work_country','work_country_id');
	}

	public function work_state(){
		return $this->belongsTo('App\Work_state','work_state_id');
	}

	public function work_locations(){
		return $this->hasMany('App\Work_location','work_city_id','id');
	}

	public function from_city(){
		return $this->hasMany('App\Trip','from_city_id','id');
	}

	public function to_city(){
		return $this->hasMany('App\Trip','to_city_id','id');
	}
}

app/Http/Controllers/Admin/WorkCityController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DataTables;
use App\Work_city;
use App\Work_state;
use App\Work_country;
use Validator;

class WorkCityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries=Work_country::all();
        return view('admin.work_cities.work_cities',compact('countries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=array(
            'name'=>$request->get('name'),
            'work_country_id'=>$request->get('work_country_id'),
            'work_state_id'=>$request->get('work_state_id'),
            'timezone_name'=>$request->get('timezone_name'),
            'timezone'=>$request->get('timezone')
        );
        $validator = Validator::make($data,[
            'name'=>"required",
            'work_country_id'=>"required",
            'work_state_id'=>"required",
            'timezone'=>"required",
            'timezone_name'=>"required"
        ]);

        if ($validator->fails()) { 
            return response()->json(['status'=>false,'message'=>$validator->messages()->first()]);            
        }       
        Work_city::create($data);
        return response()->json(['status'=>true,'message'=>'City added successfully.']);  
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Work_city  $work_city
     * @return \Illuminate\Http\Response
     */
    public function show(Work_city $work_city)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Work_city  $work_city
     * @return \Illuminate\Http\Response
     */
    public function edit(Work_city $work_city)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Work_city  $work_city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Work_city $work_city)
    {
        $data=[
            'name'=>$request->get('name'),
            'work_country_id'=>$request->get('work_country_id'),
            'work_state_id'=>$request->get('work_state_id'),
            'timezone_name'=>$request->get('timezone_name'),
            'timezone'=>$request->get('timezone')
        ];
        $validator = Validator::make($data,['name'=>"required",
            'work_country_id'=>'required',
            'timezone'=>"required",
            'timezone_name'=>"required"
        ]);

        if ($validator->fails()) { 
            return response()->json(['status'=>false,'message'=>$validator->messages()->first()]);            
        }       
        Work_city::where('id',$work_city->id)->update($data);
        return response()->json(['status'=>true,'message'=>'City updated successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Work_city  $work_city
     * @return \Illuminate\Http\Response
     */
    public function destroy(Work_city $work_city)
    {
        Work_city::where('id',$work_city->id)->delete();
        return response()->json(['status'=>true,'message'=>'City deleted successfully.']); 
    }

    public function show_work_cities(Request $request){
        return Datatables::of(Work_city::select('id','name','work_country_id','work_state_id','timezone_name','timezone')->with('work_country')->with('work_state'))
        ->addIndexColumn()
        ->addColumn('country', function($city){
            return $city->work_country['name'];
        })
        ->addColumn('state', function($city){
            return $city->work_state['name'];
        })
        ->editColumn('timezone', function($city){
            return $city['timezone'].'('.$city['timezone_name'].')';
        })
        ->addColumn('action', function($city){
            return '<a href="javascript:void(0)" class="pr-5" title="Edit" data-toggle="modal" data-target="#cityEdit_modal" data-id="'.$city->id.'" data-name="'.$city->name.'" data-timezone="'.$city->timezone.'" data-timezone_name="'.$city->timezone_name.'" data-country="'.$city->work_country_id.'" data-state="'.$city->work_state_id.'">
            <i class="zmdi zmdi-edit"></i>
            </a>';
        })
        ->rawColumns(['action'])
        ->make(true);
    }


    public function get_state($id){
        $states=Work_state::where('work_country_id',$id)->get();
        $html='<option value="">Select City</option>';
        foreach ($states as $key => $state) {
            $html.='<option value="'.$state->id.'">'.$state->name.'</option>';
        }
        if(count($states) <= 0){
            $html.='<option value="">No state Found.</option>';
        }
        return $html;//die();
    }
}

resources/views/admin/work_cities/work_cities.blade.php
@extends('admin.layouts.admin-app')

@section('content')

@section('css_ref')
<link href="{{ asset('admin_assets/vendors/bower_components/datatables/media/css/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css"/>
@endsection
<!-- Main Content -->
<div class="page-wrapper">

	<div class="container-fluid">

		<!-- Title -->
		<div class="row heading-bg">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h5 class="txt-dark">Work Cities List</h5>
			</div>
			<!-- Breadcrumb -->
			<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
				<ol class="breadcrumb">
					<li><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
					<li class="active"><span>Work Cities List</span></li>
				</ol>
			</div>
			<!-- /Breadcrumb -->
		</div>
		<!-- /Title -->

		<!-- Row -->
		<div class="row">
			<div class="col-sm-12">
				<div class="panel panel-default card-view settableboxadd">
					<div class="panel-heading">
						<div class="pull-left">
							<h6 class="panel-title txt-dark"></h6>
						</div>
						<div class="pull-right">
							<a href="javascript:void(0);" class="btn btn-success" data-toggle="modal" data-target="#cityAdd_modal" data-title="Add"><span class="btn-text">Add</span></a>								
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="panel-wrapper collapse in">
						<div class="panel-body">
							<div class="table-wrap">
								<div class="table-responsive">
									<table id="workCity" class="table  table-striped table-bordered mb-0 alltextbtnandiconset1 iconsize_set pb-30" >
										<thead>
											<tr>
												<th>Sr. No</th>
												<th>City</th>
												<th>Country</th>
												<th>Action</th>
											</tr>
										</thead>
										<tfoot>
											<tr>
												<th>Sr. No</th>
												<th>City</th>
												<th>Country</th>
												<th>Action</th>
											</tr>
										</tfoot>
										<tbody>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>	
			</div>
		</div>
		<!-- /Row -->
	</div>

	@include('admin.layouts.footer')
</div>
<div class="modal fade in" id="cityAdd_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" style="">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
				<h5 class="modal-title" id="exampleModalLabel1">Add Work City</h5>
			</div>
			<form id="addCityFrm" data-toggle="validator">
				<div class="modal-body">
					<div class="form-group">
						<label for="recipient-name" class="control-label mb-10 title">City:</label>
						<input type="text" name="name" class="form-control" required="">
						<div class="help-block with-errors"></div>
					</div>
					<div class="form-group">
						<label for="recipient-name" class="control-label mb-10 title">Country:</label>
						<select name="work_country_id" required=""  class="form-control">
							<option value=""></option>
							@foreach($countries as $country)
							<option value="{{$country->id}}">{{$country->name}}</option>
							@endforeach
						</select>
						<div class="help-block with-errors"></div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Add</button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="modal fade in" id="cityEdit_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" style="">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
				<h5 class="modal-title" id="exampleModalLabel1">Add Work Country</h5>
			</div>
			<form id="editCityFrm" data-toggle="validator">
				<div class="modal-body">
					<div class="form-group">
						<label for="recipient-name" class="control-label mb-10 title">City:</label>
						<input type="text" name="name" class="form-control" required="" id="city">
						<div class="help-block with-errors"></div>
					</div>
					<div class="form-group">
						<label for="recipient-name" class="control-label mb-10 title">Country:</label>
						<select name="work_country_id" id="work_country_id" required=""  class="form-control">
							<option value=""></option>
							@foreach($countries as $country)
							<option value="{{$country->id}}">{{$country->name}}</option>
							@endforeach
						</select>
						<div class="help-block with-errors"></div>
					</div>
					<input type="hidden" name="city_id" id="city_id" value="">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Update</button>
				</div>
			</form>
		</div>
	</div>
</div>
<!-- /Main Content -->
@section('scripts')
<script>
	$('#workCity').DataTable({
		pageLength:10,
		// processing: true,
		serverSide: true,
		// sServerMethod: "POST",
		lengthMenu: [[10, 50, 100, -1], [10, 50, 100, "All"]],
		ajax: {
			type: "post",
			url: "{{ route('admin.work_cities.work_cities') }}",
			data: function ( d ) {
				d._token = "{{ csrf_token() }}";
			},
			complete:function(){
				if( $('[data-toggle="tooltip"]').length > 0 )
					$('[data-toggle="tooltip"]').tooltip();
			}
		},
		columns:[
		{ data:'DT_RowIndex',name:'id' },
		{ data:'name',name:'name' },
		{ data:'country',name:'country' },
		{ data:'action',name:'action', orderable:false, searchable:false },
		]
	});

	$( "#addCityFrm" ).submit(function( event ) {
		event.preventDefault();
		var data=$( "#addCityFrm" ).serialize();
		$.ajax({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			},
			method:'POST',
			url:'{{route('admin.work_cities.store')}}',
			data:data,
			dataType: "json",
			success:function(data) {
				switch (data.status) {
					case true:
					toastr.success(data.message);
					location.reload();
					break;
					case false:
					toastr.warning(data.message);
					break;
					default:
					toastr.error("You are not Authorized to access this page");
					break;
				}
			},
		});
	});

	$('#cityEdit_modal').on('shown.bs.modal', function(e) {
		$("#city_id").val($(e.relatedTarget).data('id'));
		$("#city").val($(e.relatedTarget).data('name'));
		$("#work_country_id").val($(e.relatedTarget).data('country'));
	});

	$( "#editCityFrm" ).submit(function( event ) {
		event.preventDefault();
		var data=$( "#editCityFrm" ).serialize();
		$.ajax({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			},
			method:'PUT',
			url:'{{route('admin.work_cities.update','')}}/'+$("#city_id").val(),
			data:data,
			dataType: "json",
			success:function(data) {
				switch (data.status) {
					case true:
					toastr.success(data.message);
					location.reload();
					break;
					case false:
					toastr.warning(data.message);
					break;
					default:
					toastr.error("You are not Authorized to access this page");
					break;
				}
			},
		});
	});

	function deleteCity(id){ 
		var token = "{{ csrf_token() }}";

		swal({
			title: "Are you sure?",   
            text: "You will not be able to recover this information!",   
            type: "warning",   
            showCancelButton: true,   
            confirmButtonColor: "#e69a2a",   
            confirmButtonText: "Yes, delete it!",   
            cancelButtonText: "No, cancel please!",   
            closeOnConfirm: false,   
            closeOnCancel: false 
		},
		function(isConfirm){   
			if (isConfirm) {
				$.ajax({
					headers: {
						'X-CSRF-TOKEN':  "{{ csrf_token() }}"
					},
					method:'DELETE',
					url:'{{route('admin.work_cities.destroy','')}}/'+id,
					dataType: "json",
					success:function(data) {
						switch (data.status) {
						case 200:
						table.ajax.reload();
						swal("Deleted!", "Your information has been deleted.", "success");  
						toastr.success(data.message);
						break;
						case 500:
						toastr.error(data.message);
						break;
						default:
						toastr.error("You are not Authorized to access this page");
						break;
					}
					},
				});
			} else {
				swal("Cancelled", "Your information is safe! :)", "error"); 
			}
		});
	}
</script>
@endsection
@endsection