routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('welcome');
// });

// Route::get('socket', 'Admin\DashboardController@socket');
// Route::get('socket1', 'Admin\DashboardController@socket1');

Route::get('/rfpanel/become_driver', function() {
	return redirect()->route('website.become_driver');
});

Route::get('socket_driver', 'GeneralController@socket');
Route::get('socket_rider', 'GeneralController@socket_patient');


Route::group(['namespace'=>'website','as'=>'website.'],function(){
	Route::get('/','HomeController@index')->name('home');
	Route::get('become_driver','HomeController@becomeDriver')->name('become_driver');
	Route::get('cities','HomeController@cities')->name('cities');
	Route::get('driver_requirements','HomeController@driverRequirements')->name('driver_requirements');
	Route::get('privacy_policy','HomeController@privacyPolicy')->name('privacy_policy');
	Route::get('getting_started','HomeController@gettingStarted')->name('getting_started');
	Route::post('addBecomeDriver','HomeController@addBecomeDriver')->name('addBecomeDriver');
	Route::get('contact_us','HomeController@contactUs')->name('contact_us');
	Route::get('faq','HomeController@faq')->name('faq');
	Route::get('how_to_ride','HomeController@howToRide')->name('how_to_ride');
	Route::get('fares','HomeController@fares')->name('fares');
});

Route::group(['prefix'=> 'rfupanel', 'namespace'=>'Admin\Auth','as'=>'admin.'],function(){

	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['prefix'=> 'rfupanel', 'namespace'=>'Admin','as'=>'admin.','middleware'=>'auth:admin'],function(){
	Route::get('/', 'DashboardController@dashboard')->name('dashboard');
	// other dashboards
	Route::get('/payment', 'DashboardController@payment')->name('payment');

	Route::get('/secondDashboard', 'DashboardController@secondDashboard');
	Route::get('/thirdDashboard', 'DashboardController@thirdDashboard');
	Route::get('/fourthDashboard', 'DashboardController@fourthDashboard');

	/** driver / Rider  **/
	Route::get('getUsersList', 'UserController@getUsersList')->name('users.getUsersList');
	Route::get('userProfileApprove/{id}','AdminUserAccessController@user_profile_approve_admin')->name('users.approve');
	Route::Resource('users','UserController');
	Route::get('editRiderProfile','UserController@edit_rider_profile')->name('rider.edit.profile.data');
	Route::post('riders/update/{id}', 'UserController@update')->name('users.update');

	Route::Resource('drivers','DriverController');

	/* route for listing trip for user and driver */
	Route::get('trips/{id}','TripController@list_user_trips')->name('displayUserTrips');
	Route::get('triplist/{id}','TripController@list_driver_trips')->name('displayDriverTrips');

	/* Admin approve driver profile */
	Route::get('/driverProfileApprove','AdminUserAccessController@driver_profile_approve_admin')->name('driver.approve');
	/* user details page */
	Route::get('/driverDetails/{id}','DriverController@driver_details_function')->name('driver.show');

	/*route for payment listing */
	Route::get('payments/{id}','PaymentController@list_user_payments')->name('displayUserpayments');
	Route::get('paymentlist/{id}','PaymentController@list_Driver_payments')->name('displayDriverpayments');

	/*code for add driver profile */
	Route::get('adddriver_profile/{id}','DriverController@adddriver_profile')->name('adddriver_profile');
	Route::get('addDriverProfile/{id}','DriverController@show_driver_profile')->name('addDriverProfile');
	Route::post('addDriveraddress/{id}','DriverController@add_driver_address')->name('updateDriverProfile');

	// Route::post('drivers/update/{id}', 'DriverController@update')->name('drivers.update');

	/* Manage driver documents */
	Route::Resource('driverManageDocuments','DriverManageController');
	Route::get('drivermanageDocument/{id}','DriverManageController@view')->name('driverManageDocuments.view');

	/*code for documents */
	Route::get('listDocuments/{id}','DriverCarDetailsController@list_documents')->name('listDocuments');
	Route::post('submitDocuments','DriverCarDetailsController@submit_Documents')->name('submitDocuments');
	Route::get('deleteDocuments/{id}','DriverCarDetailsController@delete_document')->name('deleteDocuments');

	/* trip history */
	Route::get('tripHistory','TripController@trip_history_upcoming')->name('upcoming.trips');
	Route::get('completeHistory','TripController@trip_history_complete')->name('complete.trips');
	Route::get('triplist','TripController@get_trip_list')->name('trip.history');
	Route::get('tripdetails/{id}','TripController@get_trip_details')->name('trip.details');
	Route::get('giveBookingRefund/{booking_id}','TripController@giveBookingRefund')->name('trip.giveBookingRefund');
	Route::post('bookingRefund/{booking_id}','TripController@bookingRefund')->name('trip.bookingRefund');

	Route::get('chargeDriver/{trip_id}','TripController@chargeDriver')->name('trip.chargeDriver');
	Route::post('tripCharge/{trip_id}','TripController@tripCharge')->name('trip.tripCharge');

	/* code for list vehicles */
	Route::get('listVehicles/{id}','DriverCarDetailsController@list_vehicles')->name('ViewVehicalesList');
	Route::get('addVehicles/{id}','DriverCarDetailsController@add_vehicles_page')->name('addVehicles');
	Route::post('addVehiclesform','DriverCarDetailsController@add_vehicles')->name('addVehiclesForm');
	Route::post('addVehicles','DriverCarDetailsController@delete_vehicles')->name('deleteVehiclesForm');

	/* Payment history */
	Route::get('paymentHistory','PaymentController@get_payment_history')->name('payment_history');
	Route::get('paymentlist','PaymentController@get_payment_list')->name('payment.history');
	Route::get('/totalEarning', 'PaymentController@totalEarning')->name('totalEarning');

	/* Route for add car details*/
	Route::post('addDriverCarDetails','DriverController@add_car_details')->name('add.carDetails');
	/* driver car details */
	Route::Resource('driverCarDetails','DriverCarDetailsController');
	Route::post('DriverCarDetailsList','DriverCarDetailsController@car_details_list')->name('driverCarDetails.list');
	Route::post('DriverCarDetailsEdit','DriverCarDetailsController@get_edit_car_data')->name('get.edit.data');

	Route::get('getProducts', 'GlobalSettingController@show_products_page')->name('products.product');
	Route::apiResource('products','GlobalSettingController');
	Route::post('appSettingStore', 'GlobalSettingController@appSettingStore')->name('products.appSetting');
	Route::post('adminFees', 'GlobalSettingController@adminFees')->name('products.adminFees');

	Route::post('get_work_countries', 'WorkCountryController@show_work_countries')->name('work_countries.work_countries');
	Route::Resource('work_countries','WorkCountryController');

	Route::post('get_work_cities', 'WorkCityController@show_work_cities')->name('work_cities.work_cities');
	Route::Resource('work_cities','WorkCityController');
	Route::get('get_state/{id}', 'WorkCityController@get_state')->name('work_city.get_state');



	/* STATE */
	Route::post('create_state', 'WorkStateController@create_state')->name('create_state');
	Route::get('getStateList', 'WorkStateController@getStateList')->name('getStateList');
	Route::put('update_state/{id}', 'WorkStateController@update_state')->name('update_state');

	Route::post('get_work_locations', 'WorkLocationController@show_work_locations')->name('work_locations.work_locations');
	Route::get('get_cities_by_country/{id}', 'WorkLocationController@get_cities_by_country')->name('work_locations.get_cities_by_country');
	Route::Resource('work_locations','WorkLocationController');

	//Route::post('getJobList', 'JobHistoryController@getJobList')->name('jobhistory.getJobList');
	//Route::apiResource('jobhistory','JobHistoryController');

	/* Admin approve user profile and send mail */
	Route::get('approveMail','UserController@user_approval_comment_mail')->name('approval.mail');
	/* Admin approve user profile and send mail */
	Route::get('approvedMail','DriverController@driver_approval_comment_mail')->name('approvals.mail');


	/* Car Route */
	Route::Resource('carCompany','CarCompanyController');
	Route::post('carCompanyList','CarCompanyController@list')->name('carcompany.list');
	Route::post('carCompanyname','CarCompanyController@get_edit_company_name')->name('carcompany.edit.name');

	/* OFFICE  INFOMATION*/
	Route::Resource('officeInformations','OfficeInformationController');
	Route::get('createOffice','OfficeInformationController@createOffice')->name('office.create');
	Route::post('addOffice','OfficeInformationController@addOffice')->name('office.add');
	Route::get('listOffice','OfficeInformationController@listOffice')->name('office.list');
	Route::delete('deleteOffice','OfficeInformationController@deleteOffice')->name('office.delete');
	Route::get('editOffice/{id}','OfficeInformationController@editOffice')->name('office.edit');
	Route::post('updateOffice','OfficeInformationController@updateOffice')->name('office.update');

	/* Car types*/
	Route::Resource('carType','CarTypesController');

resources/views/admin/charge_driver.blade.php
@extends('admin.layouts.admin-app')
<?php //die(); ?>
@section('content') 
<div class="page-wrapper">
    <!-- Main Content -->
    <div class="container-fluid pt-25">
        <div class="back_button">
            <a href="{{route('admin.trip.details',$trip_id)}}"><button class="btn btn btn-success">Back</button></a>
        </div>
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h5 class="txt-dark">Charge Driver</h5>
            </div>
          <!-- Breadcrumb -->
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                    <li><a href="{{route('admin.trip.details',$trip_id)}}">Trip Detail</a></li>
                    <li class="active"><span>Charge Driver</span></li>
                </ol>
            </div>
            <!-- /Breadcrumb -->
        </div>
    <!--  -->
   
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default card-view BoxDesignCoverInerCla1">
                    <div class="panel-heading">
                        <div class="pull-left">
                            
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="form-wrap">
                                <form  method="POST" id="refundForBookingFrm" data-toggle="validator">
                                    <div class="colmd12fullwidth">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left" for="example-email"><span class="help">Amount</span></label>
                                                <input type="text" id="amount" name="amount" class="form-control" placeholder="Amount" required=""  value="">
                                                <input type="hidden" name="trip_id" id="trip_id" value="{{$trip_id}}">
                                                <div class="help-block with-errors"></div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="colmd12fullwidth2">
                                        <button type="submit" id="Update" data-loading-text="<i class='fa fa-spinner'></i>" class="btnsetm">Charge</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Row -->
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">

    

    /*code for add driver address*/

    $('#refundForBookingFrm').submit(function(e){
        e.preventDefault();
        form=$('#refundForBookingFrm');
        var formData = new FormData(form[0]);       
        var id = $('#trip_id').val();

        if ($('#refundForBookingFrm').validator('validate').has('.has-error').length === 0) {

            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method:'POST',
                url:"{{route('admin.trip.tripCharge','')}}/"+id,
                data:formData,
                cache:false,
                processData: false,
                contentType: false,
                 beforeSend: function(){
                   $('#update').button('loading');
                },
                success:function(data) {
                    switch (data.status) {
                        case true:
                        toastr.success(data.message);
                        location.replace('{{route('admin.trip.details',$trip_id)}}');
                        break;
                        case false:
                        toastr.error(data.message);
                        break;
                    }
                },
                complete: function(){
                  $('#update').button('reset');
                }
            });
        }
    });
</script>
@endsection

resources/views/admin/global-settings.blade.php
@extends('admin.layouts.admin-app')
@section('styles')
<style type="text/css">
.disply_temp, .disply_transfer{
	display: none;
}
</style>
@endsection
@section('content')

<div class="adminright_detlisdivbox">
		<div class="setting_detlisdivbox">
			<div class="vehicles_topdivbox">
				<ul>
					<li>
						<div class="vehicles_innertextbox">
							<h4>Vehicles</h4>
							<a href="{{ route('admin.carCompany.index') }}"><img src="{{ asset('admin_assets/svg/right-arrow.svg') }}"></a>
							<p>{{ $total_vehicles }} Vehicles</p>
						</div>
					</li>
					<li>
						<div class="vehicles_innertextbox">
							<h4>Locations</h4>
							<a href="{{ route('admin.work_countries.index') }}"><img src="{{ asset('admin_assets/svg/right-arrow.svg') }}"></a>
							<p>{{ $total_location }} Locations</p>
						</div>
					</li>
					<li>
						<div class="vehicles_innertextbox">
							<h4>Active Cities</h4>
							<a href="{{ route('admin.officeInformations.index') }}"><img src="{{ asset('admin_assets/svg/right-arrow.svg') }}"></a>
							<p>{{ $total_city }} Cities</p>
						</div>
					</li>
				</ul>
			</div>
			<div class="ridechimpfees_mandetlisdiv">
				<div class="ridechimpfees_detlisbox">
					<form data-toggle="validator" role="form" novalidate="true" id="rideChimpForm">
						<p>Ridechimp Fees</p>
						<div class="feesinput_lefttext">
							<span>%</span>
						</div>
						<div class="ridechimpfeesinput_text">
							<input type="text" name="admin_cent" placeholder="00.00" value="{{ $admin_statistic->admin_cent }}" required="">
						</div>
						<div class="ridechimpfeessave_butten">
							<button type="submit">SAVE</button>
						</div>
					</form>
				</div>
			</div>
			<div class="ridechimpfees_mandetlisdiv">
				<form class="form" data-toggle="validator" role="form" novalidate="true" id="appSettingForm">
					<div class="ridechimpfees_detlisbox">
						<p>App Settings</p>
						<div class="maintanacradio_button">
							<p>Maintenance Mode</p>
								<div class="switch-field">
									<input type="radio" id="switch_left" name="maintanance_mode" value="0" checked @if(isset($maintanance->maintanance_mode) && $maintanance->maintanance_mode=="0"){{'checked'}}@endif>
									<label for="switch_left">OFF</label>
									<input type="radio" id="switch_right" name="maintanance_mode" value="1" @if(isset($maintanance->maintanance_mode) && $maintanance->maintanance_mode=="1"){{'checked'}}@endif>
									<label for="switch_right">ON</label>
								</div>
						</div>
						<div class="appversion_detlisdiv">
							<p>Android App Version</p>
							<input type="text" name="android_version" placeholder="0.0" value="@if($maintanance != ''){{$maintanance->android_version}}@endif" required="">
						</div>
						<div class="appversion_detlisdiv">
							<p for="ios_version">IOS App Version</p>
							<input type="text" name="ios_version" placeholder="0.0" value="@if($maintanance != ''){{$maintanance->ios_version}}@endif" id="ios_version" required="">
						</div>
						<div class="bottomsave_btn">
							<button type="submit">SAVE</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>




@endsection
@section('scripts')
<script>
		//APP SETTING
		$( "#appSettingForm" ).submit(function( event ) {
			event.preventDefault();
			var data=$("#appSettingForm").serialize();
			$.ajax({
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				method:'POST',
				url:'{{route('admin.products.appSetting')}}',
				data:data,
				dataType: "json",
				beforeSend:function(){},
				success:function(data) {
					switch (data.status) {
						case true:
						toastr.success(data.message);
						break;
						case false:
						toastr.error(data.message);
						break;
					}
				},
			});
		});


		//RIDECHIMP FEES
		$("#rideChimpForm" ).submit(function( event ) {
			event.preventDefault();
			var data=$("#rideChimpForm").serialize();
			$.ajax({
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				method:'POST',
				url:'{{route('admin.products.adminFees')}}',
				data:data,
				dataType: "json",
				beforeSend:function(){},
				success:function(data) {
					switch (data.status) {
						case true:
						toastr.success(data.message);
						break;
						case false:
						toastr.error(data.message);
						break;
					}
				},
			});
		});

</script>
@endsection

resources/views/admin/refund.blade.php
@extends('admin.layouts.admin-app')
<?php //die(); ?>
@section('content') 
<div class="page-wrapper">
    <!-- Main Content -->
    <div class="container-fluid pt-25">
        <div class="back_button">
            <a href="{{route('admin.trip.details',1)}}"><button class="btn btn btn-success">Back</button></a>
        </div>
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h5 class="txt-dark">Booking Refund</h5>
            </div>
          <!-- Breadcrumb -->
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                    <li><a href="{{route('admin.trip.details',1)}}">Trip Detail</a></li>
                    <li class="active"><span>Booking Refund</span></li>
                </ol>
            </div>
            <!-- /Breadcrumb -->
        </div>
    <!--  -->
   
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default card-view BoxDesignCoverInerCla1">
                    <div class="panel-heading">
                        <div class="pull-left">
                            
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="form-wrap">
                                <form  method="POST" id="refundForBookingFrm" data-toggle="validator">
                                    <div class="colmd12fullwidth">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left" for="example-email"><span class="help">Amount</span></label>
                                                <input type="text" id="amount" name="amount" class="form-control" placeholder="Amount" required=""  value="">
                                                <input type="hidden" name="booking_id" id="booking_id" value="{{$booking_id}}">
                                                <div class="help-block with-errors"></div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="colmd12fullwidth2">
                                        <button type="submit" id="Update" data-loading-text="<i class='fa fa-spinner'></i>" class="btnsetm">Refund</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Row -->
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">

    

    /*code for add driver address*/

    $('#refundForBookingFrm').submit(function(e){
        e.preventDefault();
        form=$('#refundForBookingFrm');
        var formData = new FormData(form[0]);       
        var id = $('#booking_id').val();

        if ($('#refundForBookingFrm').validator('validate').has('.has-error').length === 0) {

            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method:'POST',
                url:"{{route('admin.trip.bookingRefund','')}}/"+id,
                data:formData,
                cache:false,
                processData: false,
                contentType: false,
                 beforeSend: function(){
                   $('#update').button('loading');
                },
                success:function(data) {
                    switch (data.status) {
                        case true:
                        toastr.success(data.message);
                        location.replace('{{route('admin.trip.details',$trip_id)}}');
                        break;
                        case false:
                        toastr.error(data.message);
                        break;
                    }
                },
                complete: function(){
                  $('#update').button('reset');
                }
            });
        }
    });
</script>
@endsection

resources/views/admin/trip_details.blade.php
<?php use Carbon\Carbon; ?>
@extends('admin.layouts.admin-app')
<style type="text/css">
b, strong {
    font-weight: 700 !important;
}
li {
    padding-bottom: 10px !important;
}
.success{
    color:#0DC07F !important;    
}
.danger{
    color:#DC143C !important;
}
.info{
    color:#FA942D !important;   
}

</style>
@section('content')
<div class="adminright_detlisdivbox">
    <div class="setting_detlisdivbox">
        <div class="ordersbooked_detlis">
            <h4>TRIP#{{ $trip->id }}</h4>
            <P>Trip Status:
                @if($trip->status == 'scheduled')
                <span> Scheduled </span>
                @elseif($trip->status == 'started')
                <span> Started </span>
                @elseif($trip->status == 'completed')
                <span> Completed </span>
                @elseif($trip->status == 'cancelled')
                <span class="text-danger"> Cancelled by driver </span>
                @endif
                
            </P>
            @if($trip->status == 'cancelled')
            <p>Reason For Cancellation : 
                {{$trip->cancelled_reason}}
            </p>
            @endif

        </div>
    </div>
    <div class="bookingdetlis_text">
        <h4>Booking Details</h4>
        <?php $driver_penalty = false; ?>
        @forelse ($trip->bookings as $booking)
        <p>
            <a href="{{ route('admin.orderDetails',$booking->id) }}">
                <span>BOOKING ID #{{ $booking->id }}</span>
            </a>
        </p>
        <p>Booked By: {{ $booking->user->first_name .' '.$booking->user->last_name }}
            <a href="{{ route('admin.users.show',$booking->user->id) }}"> <span>(View Profile)</span></a>
        </p>
        <p>Booked Date: {{ $booking->created_date.' MDT' }}</p>
        <p>Seats Booked: {{ $booking->seats }}</p>
        <p>Booking Status : 
            @if($booking->status == 'pending')
            <span> Pending </span>
            @elseif($booking->status == 'confirmed')
            <span> Confirmed </span>
            @elseif($booking->status == 'cancelled')
            <span class="text-danger"> Cancelled by rider </span>
            @elseif($booking->status == 'picked_up')
            <span > Picked up </span>
            @elseif($booking->status == 'no_show')
            <span class="text-danger"> No Show </span>
            @elseif($booking->status == 'drop_off')
            <span> Dropped Off </span>
            @elseif($booking->status == 'rejected')
            <span class="text-danger"> Rejected </span>
            @endif
        </p>
        @if($booking->status == 'cancelled')
        <p>Reason For Cancellation : 
            {{$booking->cancellation_reason}}
        </p>
        @endif
        @if($booking->status == 'rejected')
        <p>Reason For Decline : 
            {{$booking->decline_reason}}
        </p>
        @endif

        <p>Payment Status : 
            <?php
            $payment_status = 'Pending';
            if($booking->payment != ''){
                $payment_status = 'Processed';
            }

            if($booking->status == 'cancelled' ||  $booking->trip->status == 'cancelled'){
                if($booking->payment['refunded_id'] == ''){
                    $payment_status = 'Refund Pending';
                } else {
                    $payment_status = 'Refunded';
                }
            }

            if($booking->status == 'rejected' && $booking->payment == ''){
                $payment_status = 'Not Charged';
            }

            echo $payment_status;
            ?>
            @if($booking->driver_not_show_at != '' && $booking->payment['refunded_id'] == '' && $booking->trip->dropoff_time < Carbon::today() && $booking->trip->status == 'scheduled')
            <?php $driver_penalty = true; ?>
            <a href="{{ route('admin.trip.giveBookingRefund',$booking->id) }}"> <span>Send Refund</span></a>             @endif
        </p>
        <br>

        @empty
        <p>No data found</p>
        @endforelse

    </div>
    @if($driver_penalty && $trip->driver_penalties == '')
    <div class="ridechimpfeessave_butten" style="width: 55%;padding-top: 20px;">
        <button type="button" id="charge_driver">ADD PENALTY TO DRIVER WALLET</button>
    </div>  
    @endif
    <div class="Tripdetlis_mandivtextbox">
        <div class="Tripdetlis_textbox">
            <h4>Trip Datails</h4>
            <p>Travel Date: {{ $trip->trip_dated }}</p>
            <p>Price / seat: ${{ number_format($trip->price,2) }}</p>
        </div>
        <div class="mandivsteetleft_textbox">
            <div class="steetleft_textbox">
                <h4>From</h4>
                <h3>{{ $trip->from_location->work_city->name }}</h3>
                <p>{{ $trip->from_location->name }}</p>
            </div>
            <div class="distancearrow_div">
                <img src="{{ asset('admin_assets/svg/right-arrow.svg') }}">
            </div>
            <div class="steetleft_textbox">
                <h4>to</h4>
                <h3>{{ $trip->to_location->work_city->name }}</h3>
                <p>{{ $trip->to_location->name }}</p>
            </div>
        </div>
        <div class="mandivsteetleft_textbox">
            <div class="pickuploction_detlis">
                <p>Pick-up location & Time</p>
                <h4><!-- {{ wordwrap($trip->from_location->name,40,'\n') }} -->
                    <?php
                    echo wordwrap($trip->from_location->name,40,'<br>');
                    ?>
                    <a href="http://maps.google.com/?q={{ $trip->from_location->latitude.','.$trip->from_location->longitude }}" target="_blank"><span>(View on Map)</span></a>
                </h4>
                <h4>{{ $trip->picked_uptime.' MDT on '. $trip->trip_date->format('d-M-Y') }}</h4>

            </div>
        </div>
        <div class="mandivsteetleft_textbox">
            <div class="pickuploction_detlis">
                <p>Drop-off location:</p>
                <h4><!-- {{ $trip->to_location->name }} -->
                    <?php
                    echo wordwrap($trip->to_location->name,40,'<br>');
                    ?>
                    <a href="http://maps.google.com/?q={{ $trip->to_location->latitude.','.$trip->to_location->longitude }}" target="_blank">
                        <span>(View on Map)</span>
                    </a>
                </h4>
                <h4>{{$trip->dropoff_on}}</h4>

            </div>
        </div>
    </div> 
    @if($html != '')
    <div class="Tripdetlis_mandivtextbox">
        <div class="Tripdetlis_textbox">
            <h4>Trip Activity</h4>
        </div>

        <div class="mandivsteetleft_textbox">
            <div class="pickuploction_detlis">
                <ul>
                 {!!$html!!}

             </ul>
         </div>
     </div>
 </div>
 @endif
</div> 
</div>
@endsection

@section('scripts')
<script type="text/javascript">
    $('#charge_driver').click(function(e) {
        location.replace('{{ route('admin.trip.chargeDriver',$trip->id) }}')
    })
</script>
@endsection